### ISSUE TITLE
Possible change for macos worfklow file

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/PAM#165]
The [pamc-unit-macos.yml](https://github.com/E3SM-Project/PAM/blob/master/.github/workflows/pamc-unit-macos.yml) workflow file has the following snippet
```yaml
jobs:
  mmf-simplified-macos:
    runs-on: macos-12
```
GitHub docs do not mention a `macos-12` runner, they only mention `macos-13`, `macos-14` and `macos-latest`. Perhaps we should just run on the latter, whose name I think will always be valid?
